---
title: Base
description: Jekyll theme.
url: 
baseurl: 
lang: en
logo: 
logo_light: 
permalink: "/:title/"

template:               mordecai

author:
  email: info@blacompany.com
  phone: +1-800-354-3434
  address: 2030 West River St. <br> New York 52304

navbar:
  sticky: true
  
footer:
  background: secondary
  social: true
  address: true
  phone: true
  email: true
  copyright: Made by <a href="https://unbound.studio/">Unbound Studio</a> in Mexico City.

google_analytics: 

social_networks:
  facebook: https://www.facebook.com/
  flickr: 
  github: 
  instagram: https://www.instagram.com/
  linkedin: 
  pinterest: 
  twitter: 
  vimeo: 
  youtube: 

markdown: kramdown
highlighter: rouge
plugins:
- jekyll-seo-tag

exclude:
- vendor
- ".bundle"
- ".sass-cache"
- config
- Gemfile
- Gemfile.lock
- node_modules
- log
- tmp
- Rakefile
- package.json
- CHANGELOG
- LICENSE
- README
- "/docs"
sass:
  style: compressed

livereload: true

collections:
  # projects:
  #   output: true
defaults:
# - scope:
#     path: ''
#     type: projects
#   values:
#     layout: blocks
- scope:
    path: ''
    type: pages
  values:
    layout: blocks
